import { FaCommentDollar } from "react-icons/fa";
import { FaFileInvoiceDollar } from "react-icons/fa6";
import { MdOutlineSsidChart } from "react-icons/md";
import { FaMoneyCheck } from "react-icons/fa";

export const dataListCompany = [
  {
    id: 1,
    nameCompany: "AMZN",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "High Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 2,
    nameCompany: "TSLA",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "green",
    risk: "High Risk",
    iconRisk: FaMoneyCheck,

    summery:
      "<h3><b>$TSLA</b> just announced an acquisition of <b>$NFLX</b> at <b>$200 B.</b></h3> <p>This is an arbitrage opportunity, with the max gain being %X if the deal closes, but the possible risk is %Y  if the deal fails, If the deal success is % and therefore the recommended play is long/short $ABC</p>",
    // paragraph: "",
  },

  {
    id: 3,
    nameCompany: "ABQQ",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "green",
    risk: "High Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 4,
    nameCompany: "MSFT",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "#D94111",
    risk: "Mid Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 5,
    nameCompany: "PYPL",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "green",
    risk: "High Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 6,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 7,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 8,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 9,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 10,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Mid Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 11,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 12,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Mid Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 13,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 14,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },

  {
    id: 15,
    nameCompany: "NFLX",
    iconNameCompany: FaCommentDollar,
    companyMoney: 200,
    iconCompanyMoney: FaFileInvoiceDollar,
    chart: "-25%",
    iconChart: MdOutlineSsidChart,
    color: "red",
    risk: "Low Risk",
    iconRisk: FaMoneyCheck,
  },
];
